# Generated by Django 5.2.6 on 2025-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do site')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('x', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('copyright', models.CharField(default='Seu Nome', max_length=100, verbose_name='Copyright')),
                ('ano', models.PositiveIntegerField(default=2025, verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('inicio', 'Início'), ('sobre', 'Sobre')], max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('texto', models.TextField(blank=True)),
                ('imagem_header', models.ImageField(blank=True, null=True, upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='postagens/')),
            ],
        ),
    ]
