# Generated by Django 5.2.6 on 2025-09-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ator_rename_blog_app_delete_postagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtorImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='atores_galeria/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='website.ator')),
            ],
        ),
    ]
