# Generated by Django 5.2.6 on 2025-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_atorimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atorimagem',
            name='imagem',
            field=models.ImageField(upload_to='galeria_ator/'),
        ),
    ]
