# Generated by Django 5.2.6 on 2025-09-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_atorimagem_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtorImagem',
        ),
    ]
