# Generated by Django 5.2.6 on 2025-09-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_atorimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudopagina',
            name='pagina',
            field=models.CharField(choices=[('inicio', 'Início'), ('sobre', 'Sobre'), ('elenco', 'Elenco')], max_length=20, unique=True),
        ),
    ]
