# Generated by Django 5.2.6 on 2025-09-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_conteudopagina_pagina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='website.ator')),
            ],
        ),
    ]
